name: android-apk

on:
  workflow_dispatch:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up Java (Android build)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components
        run: |
          yes | sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0" \
                           "ndk;25.2.9519653" "cmake;3.22.1"

      - name: Install Qt via aqtinstall
        run: |
          pip install aqtinstall
          # Install Qt 6.6.3 Desktop (host tools)
          aqt install-qt linux desktop 6.6.3 gcc_64 --outputdir /opt/Qt
          # Install Qt 6.6.3 for Android (ARM64). Do not pass -m; modules listing isn't supported the same way on Android.
          aqt install-qt linux android 6.6.3 android_arm64_v8a --outputdir /opt/Qt

      - name: Install PySide6 tooling
        run: |
          pip install "PySide6==6.6.3" "PySide6-Addons==6.6.3" "shiboken6==6.6.3"

      - name: Build APK (PySide6 Android deploy)
        run: |
          export ANDROID_NDK_ROOT="$ANDROID_SDK_ROOT/ndk/25.2.9519653"
          export QT_ANDROID_DIR="/opt/Qt/6.6.3/android_arm64_v8a"
          export QT_HOST_PATH="/opt/Qt/6.6.3/gcc_64"
          export PATH="$QT_HOST_PATH/bin:$PATH"

          # Prepare wheels required by pyside6-android-deploy
          ROOT_DIR="$PWD"
          mkdir -p "$ROOT_DIR/dist-wheels"
          pip download --only-binary=:all: --no-deps -d "$ROOT_DIR/dist-wheels" \
            "PySide6==6.6.3" "PySide6-Addons==6.6.3" "PySide6-Essentials==6.6.3" "shiboken6==6.6.3"
          # Prefer the Addons wheel (contains WebView and other add-on libs)
          WHEEL_PYSIDE=$(ls "$ROOT_DIR"/dist-wheels/PySide6_Addons-6.6.3-*.whl 2>/dev/null | head -n1)
          if [ -z "$WHEEL_PYSIDE" ]; then
            WHEEL_PYSIDE=$(ls "$ROOT_DIR"/dist-wheels/PySide6-6.6.3-*.whl 2>/dev/null | head -n1)
          fi
          WHEEL_SHIBOKEN=$(ls "$ROOT_DIR"/dist-wheels/shiboken6-6.6.3-*.whl | head -n1)
          if [ ! -f "$WHEEL_PYSIDE" ] || [ ! -f "$WHEEL_SHIBOKEN" ]; then
            echo "Failed to download PySide6/shiboken6 wheels" >&2
            ls -l "$ROOT_DIR/dist-wheels" || true
            exit 1
          fi
          # Use the console script to avoid import issues with relative imports inside PySide6 scripts
          pushd android >/dev/null
          # Ensure a minimal buildozer.spec exists with arm64-v8a arch
          if [ ! -f buildozer.spec ]; then
            cat > buildozer.spec <<'EOF'
[app]
title = Surfscape
package.name = browser
package.domain = org.surfscape
source.dir = .
version = 1.0
orientation = portrait
fullscreen = 0
android.archs = arm64-v8a

[buildozer]
log_level = 2
warn_on_root = 0
EOF
          fi
          # Force arch to arm64-v8a in case the file existed
          sed -i 's/^#\?\s*android\.archs\s*=.*/android.archs = arm64-v8a/' buildozer.spec || true
          # Actual build
          pyside6-android-deploy \
            -f \
            --name "Surfscape" \
            --sdk-path "$ANDROID_SDK_ROOT" \
            --ndk-path "$ANDROID_NDK_ROOT" \
            --wheel-pyside "$WHEEL_PYSIDE" \
            --wheel-shiboken "$WHEEL_SHIBOKEN" \
            --keep-deployment-files \
            -v
          popd >/dev/null
          echo "APK artifacts:" && find . -name "*.apk" -o -name "*.aab"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: surfscape-android
          path: |
            **/*.apk
            **/*.aab
