name: Android APK

on:
  push:
    branches: [ main ]
    paths:
      - 'android/**'
      - '.github/workflows/android-apk.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'android/**'
      - '.github/workflows/android-apk.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      JAVA_VERSION: '17'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Generate Gradle wrapper (if missing)
        working-directory: android
        run: |
          if [ ! -f gradlew ] || [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
            echo "Generating Gradle wrapper..."
            gradle wrapper --gradle-version 8.7
          else
            echo "Gradle wrapper already present."
          fi

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Resolve GeckoView Version
        id: geckoview_version
        run: |
          set -e
          META_URL="https://maven.mozilla.org/maven2/org/mozilla/geckoview/geckoview/maven-metadata.xml"
          echo "Fetching $META_URL" >&2
          curl -sS "$META_URL" -o meta.xml
          # Extract latest release version (not snapshot) using grep/sed (simple XML parse)
          latest=$(grep -oE '<version>[0-9]+\.[0-9]+(\.[0-9]+)?</version>' meta.xml | sed -E 's#</?version>##g' | grep -Ev '(alpha|beta|SNAPSHOT)' | sort -V | tail -n1)
          if [ -z "$latest" ]; then
            echo "Failed to resolve GeckoView version" >&2
            exit 1
          fi
          echo "Resolved GeckoView version: $latest"
          echo "GECKOVIEW_VERSION=$latest" >> $GITHUB_ENV
          echo "version=$latest" >> $GITHUB_OUTPUT

      - name: Show Selected GeckoView Version
        run: echo "Using GeckoView version $GECKOVIEW_VERSION"

      - name: Build Debug APK
        working-directory: android
        run: GECKOVIEW_VERSION=${{ steps.geckoview_version.outputs.version }} ./gradlew assembleDebug --stacktrace

      - name: Build Release APK (unsigned)
        working-directory: android
        run: GECKOVIEW_VERSION=${{ steps.geckoview_version.outputs.version }} ./gradlew assembleRelease --stacktrace

      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: surfscape-apks
          path: |
            android/app/build/outputs/apk/debug/*.apk
            android/app/build/outputs/apk/release/*.apk
          if-no-files-found: error

      - name: Conditional Sign Release APK
        id: sign_release
        env:
          KEYSTORE_B64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}
        run: |
          set -e
          if [ -z "${KEYSTORE_B64}" ] || [ -z "${KEY_ALIAS}" ]; then
            echo "No signing secrets present; skipping signing." 
            echo "signed=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "Signing release APK with provided keystore" 
          mkdir -p keystore
          echo "$KEYSTORE_B64" | base64 -d > keystore/keystore.jks
          unsigned_apk=android/app/build/outputs/apk/release/app-release-unsigned.apk
          if [ ! -f "$unsigned_apk" ]; then
            echo "Unsigned release APK not found: $unsigned_apk" >&2
            echo "signed=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore keystore/keystore.jks -storepass "$KEYSTORE_PASSWORD" -keypass "$KEY_PASSWORD" "$unsigned_apk" "$KEY_ALIAS"
          buildToolsDir=$(ls $ANDROID_HOME/build-tools 2>/dev/null | sort -r | head -n1 || true)
          if [ -n "$buildToolsDir" ] && [ -d "$ANDROID_HOME/build-tools/$buildToolsDir" ]; then
            zipalign="$ANDROID_HOME/build-tools/$buildToolsDir/zipalign"
            apksigner="$ANDROID_HOME/build-tools/$buildToolsDir/apksigner"
            if [ -x "$zipalign" ] && [ -x "$apksigner" ]; then
              aligned_apk=android/app/build/outputs/apk/release/app-release-aligned.apk
              "$zipalign" -f 4 "$unsigned_apk" "$aligned_apk"
              "$apksigner" verify "$aligned_apk" || true
              mv "$aligned_apk" android/app/build/outputs/apk/release/app-release-signed.apk
            fi
          fi
          if [ -f android/app/build/outputs/apk/release/app-release-signed.apk ]; then
            echo "Signed APK ready." 
            echo "signed=true" >> $GITHUB_OUTPUT
          else
            echo "signed=false" >> $GITHUB_OUTPUT
          fi

      - name: Upload Signed APK
        if: ${{ steps.sign_release.outputs.signed == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: surfscape-apk-signed
          path: android/app/build/outputs/apk/release/app-release-signed.apk
          if-no-files-found: ignore
